In [38]:
from scipy.stats import randint, uniform

In [39]:
ri = randint(0, 10) # 0~9 무작위 수
ri.rvs(11) # 0~9사이 숫자 중 무작위 수를 11개 생성 

array([3, 7, 9, 4, 4, 6, 9, 6, 9, 5, 4])

In [40]:
import numpy as np

np.unique(ri.rvs(1000), return_counts=True) # 중복된 총 갯수를 함께 반환 

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([121, 101,  83, 112, 109,  97,  91,  92, 108,  86]))

In [41]:
ui = uniform(0, 1) # 0~1 사이의 무작위 실수
ui.rvs(5) # 0~1 사이 무작위 실수를 5개 생성

array([0.34628052, 0.83289691, 0.91867364, 0.63021175, 0.38509054])